services:
  web_server:
    container_name: web-server 
    image: nginx:1.28.0
    restart: always
    volumes:
      - ./build-development/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./build-development/nginx/site.conf:/etc/nginx/conf.d/default.conf
      - ./logs/nginx/access.log:/var/log/nginx/access.log
      - ./logs/nginx/error.log:/var/log/nginx/error.log
      - .:/var/www/technews
    networks:
      - technews
    ports:
      - 8080:80
    depends_on:
      - php-fpm
  php-fpm:
    container_name: php-fpm
    build:
      context: build-development/php-fpm
      dockerfile: Dockerfile
    restart: always
    volumes:
      # NOTE: volume overrides composer install command
      - .:/var/www/technews
    networks:
      - technews

  # TODO: configure mysql and redis

networks:
  technews:
    driver: bridge

