services:
  web_server:
    container_name: web-server 
    image: nginx:1.28.0
    restart: always
    volumes:
      - ./build/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./build/nginx/site.conf:/etc/nginx/conf.d/default.conf
      - ./logs/nginx/access.log:/var/log/nginx/access.log
      - ./logs/nginx/error.log:/var/log/nginx/error.log
      - .:/var/www/technews
    networks:
      - technews
    ports:
      - 8888:80
    depends_on:
      - php-fpm
      - db
  php-fpm:
    # TODO: estudar healthcheck e rodar tests antes
    container_name: php-fpm
    build:
      context: build/php-fpm
      dockerfile: Dockerfile
    restart: always
    volumes:
      # NOTE: volume overrides composer install command
      - .:/var/www/technews
    networks:
      - technews
    depends_on:
      - db
  db:
    image: mysql:8.4.5
    restart: always
    environment:
        MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
        MYSQL_USER: ${DB_USERNAME}
        MYSQL_PASSWORD: ${DB_PASSWORD}
        MYSQL_DATABASE: ${DB_DATABASE}
    volumes:
      - db_technews:/var/lib/mysql
      - ./scripts/db-scheme:/docker-entrypoint-initdb.d
    networks:
      - technews


  # TODO: configure redis

networks:
  technews:
    driver: bridge

volumes:
  db_technews:
    driver: local
